### PR TITLE
Remove additional DOM elements and CSS file

### PR DESCRIPTION
**Pull request by m-heyda**

### CODE REVIEW

**Comment by m-heyda** [comment]
It would be easier just to add container with image. No additional empty DIVs etc.
Also I thought it could be good to customize blur radius by data attribute

**Comment by tunguskha** [comment]
It's definitively better ! And pretty cool to customize blur radius.

**Comment by m-heyda** [comment]
What do you think about extracting dominant color from image if it's unsupported browser and creating shadow based on that color?

**Comment by tunguskha** [comment]
That's a good idea, but do you think it will be possible to manipulate shadow-radius in the DOM?

**Comment by m-heyda** [comment]
What do you mean by manipulate shadow-radius in the DOM ?
We can always use data attributes and if there's no such attribute we use default config

**Comment by tunguskha** [comment]
Use the default config would be better, and enlarge the shadow using calc() look like this: 

`backgroundShadow: '0 25px calc(${blurValue}px + 10px) -10px rgba(${dominantColor}, .7)`

**Pull request merged**
